# Generated by Django 3.2.8 on 2021-10-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('email_address', models.EmailField(max_length=254)),
                ('occupied', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='info_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email_address', models.EmailField(blank=True, default='optional', max_length=254, null=True)),
                ('language', models.CharField(max_length=300)),
                ('religion', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('current_city', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('social_media_account', models.CharField(blank=True, default='optional', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='users.custom_user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
