# Generated by Django 3.2.8 on 2021-10-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location_long', models.CharField(default=45.4215, max_length=1000, null=True)),
                ('location_lat', models.CharField(default=45.4215, max_length=1000, null=True)),
                ('storeimage', models.ImageField(upload_to='prim')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('productimage', models.ImageField(upload_to='prim')),
                ('stores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ordernumber', models.AutoField(primary_key=True, serialize=False)),
                ('droneid', models.CharField(default=45.4215, max_length=1000, null=True)),
                ('start_time', models.CharField(max_length=1000, null=True)),
                ('delivery_time', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(max_length=1000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.custom_user')),
                ('product', models.ManyToManyField(related_name='seat', to='stores.Products')),
            ],
        ),
        migrations.CreateModel(
            name='drones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_long', models.CharField(default=45.4215, max_length=1000, null=True)),
                ('drone_lat', models.CharField(default=45.4215, max_length=1000, null=True)),
                ('dronename', models.CharField(default=45.4215, max_length=1000, null=True)),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.orders')),
            ],
        ),
    ]
